language: julia
sudo: false
os:
  - osx
  - linux
julia:
  - release
  - nightly
matrix:
  exclude:
    - julia: release
      os: osx
notifications:
  email: false
script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("Playground")'
